### ISSUE TITLE
install error; build environment build-env not found

### ISSUE THREAD

**Issue by ghost** [ArturKlauser/raspberrypi-rstudio#1]
Fantastically helpful script file, but I am getting an error in the build-stage. 
build.sh downloaded from  github.

Also, documentation and script are a bit out of sync. No longer a need to 
deal with cross-compile issues. so this section could be deleted.

Many thanks,

Hardware/OS: Pi4 4GB Buster,

``````

pi@raspberrypi:~/build_rstudio $ ./build.sh buster build-env
Start building at 2019-11-12T18:20:15Z ...
Unsupported build stage 'build-env'

Usage: build.sh <debian-version> <build-stage>
         debian-version: stretch ... Debian version 9
                         buster .... Debian version 10
         build-stage: build-env ..... build environment
                      server-deb .... server Debian package
                      desktop-deb ... desktop Debian package
                      server ........ server runtime environment
pi@raspberrypi:~/build_rstudio $ 



```

**Comment by ghost** [comment]
Indeed two small things made everything better. 1) clone the repo, don't just download the one .sh file. This should have been obvious, but it wasn't to me. 2) You will also likely need to set up your user as a docker user, otherwise you run into docker permission problems.  See here: https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/ for how to add the user to the docker group, then reboot,  slip into the local raspberrypi-rstudio folder which  was created by the git clone, and run the for loop as described in the documentation for this package.  If I get a moment I will write up a revised help file and send a pull request. Many thanks.

**Comment by ArturKlauser** [comment]
* for 1) Did checking out the whole repository and running build.sh in it fix your original problem?
* for 2) Do you mean the docker setup you have to do on the host (RPi or otherwise) before you can run the docker commands from this project?
  * My assumption was that you have a working docker environment already so that at least a *docker hello world* works. But I should probably explicitly state that in the description and point to the docker *getting started* doc.

**Comment by ghost** [comment]
Many thanks for the changes and modifications.   With the comments, the compile was dead easy., and the whole process concluded without any obvious errors about 12 hours later.  However, if the objective was to produce docker images to run and/or .deb files to install, these files are no where to be found (I did a recursive search of the whole file system).   Would you like me to open this as a new issue?  Many thanks for the extra effort this is requiring.

**Comment by ArturKlauser** [comment]
Did you try run `docker images` to list the images in your local docker cache? Do you see them there?

In the file system the docker images are not stored by their name but by their sha256 hexadecimal *image id*, which is probably why you haven't found what you were looking for. The [Getting the .deb Package Files](https://github.com/ArturKlauser/raspberrypi-rstudio#getting-the-deb-package-files) section of the documentation explains how you can extract the .deb packages from the respective images.

**Comment by aetiologicCanada** [comment]
Artur, My challenge is that I see no new files in the repo, nor elsewhere in the filesystem.  Although I ran the .build.sh script from within the repo, and it was clearly busy installing various files, updating etc and seemed to declare no errors, there are just the two script files, the README file in the head folder, and the docker file which has the four files you expect. There are no new folders and no new files.  Am I looking in the wrong folder? There are also no files/folder with "rstudio" or "arturklauger"  anywhere on the system. This is a Pi4 running buster. I am very puzzled. Many thanks,

**Comment by ghost** [comment]
Lovely. Required one set up package updates (which I neglected to write down) but now workstation and serve working fine both locally and via docker. Many thanks.
