### ISSUE TITLE
RStudio Password

### ISSUE THREAD

**Issue by Stoevne** [ArturKlauser/raspberrypi-rstudio#11]
Dear Artur,

I just installed the most recent RStudio Server Buster version from https://github.com/ArturKlauser/raspberrypi-rstudio/releases.
Thanks a lot for your work. However, I was not able to figure out the username and password. Could you please help me out with the standard username and password?

Thanks a lot!

**Comment by ArturKlauser** [comment]
If you're running the [docker image](https://github.com/ArturKlauser/raspberrypi-rstudio#running-rstudio-server) the credentials are:
Username: rstudio
Password: raspberry

If you have [installed the server .deb package](https://github.com/ArturKlauser/raspberrypi-rstudio#installing-rstudio-natively-on-your-raspberry-pi) you use whatever credentials you already have on your Raspberry, i.e. your own user.
